version: "3.7"
services:
    # image project
    app:
        container_name: laravel-livewire
        build:
            args:
                user: chacal
                uid: 1000
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            - TZ=America/Bahia
        depends_on:
            - redis
        networks:
            - livewire

    # nginx
    nginx:
        container_name: nginx-app
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
            # - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./docker/certificate/:/etc/nginx/certs
        networks:
            - livewire

    # queue
    queue:
        container_name: queue-app
        image: especializati/laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        build:
            args:
                user: chacal
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - livewire

    # redis
    redis:
        container_name: redis-app
        image: redis:latest
        networks:
            - livewire

networks:
    livewire:
        driver: bridge
